name: Build
on:
  push:
    branches:
      #TODO: remove this
      - add-automation
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          resume.tex
    #TODO: is there a way to make only the most recent version available?
    # - name: Upload PDF file
    #   uses: actions/upload-artifact@v4
    #   with:
    #     path: resume.pdf
